### ISSUE TITLE
clusterm does not restore state on restart.

### ISSUE THREAD

**Issue by vvb** [contiv/cluster#66]
Clusterm was restarted because of a earlier panic. `clusterctl nodes get` do not reflect the state of the nodes earlier to the panic. All nodes show up as 

```
        "status": "Unallocated",
        "prev-status": "Incomplete",
        "state": "Discovered",
        "prev-state": "Unknown"
```

**Comment by mapuri** [comment]
@vvb The `status` and `state` should have been restored from collins. `prev-state` and `prev-status` are kept in memory and lost on restart. These are meant for debuggability and might be ok to not restore in case of process restart as they don't impact correct functioning of cluster-mgr.

Do you happen to have the `state` and `status` values of the nodes from before the crash? Are they being restored correctly?

**Comment by vvb** [comment]
@mapuri The `status` was `Allocated` and `state` was `Discovered`. So, the status did not restore back. I am keeping an eye for it, when I see it the next time..

**Comment by mapuri** [comment]
sure, thanks @vvb 

we can may be add a systemtest for this scenario i.e. start clusterm, commission a node, restart clusterm and verify node's state

Most of the utilities should be already there in `management/src/systemtests/cli_test.go`, so adding this should be straight-forward. Let me know if you would like to take a stab at it.

**Comment by mapuri** [comment]
@vvb I added a system test to validate node state restore functionality ( #83 ). It works with boltdb but with collins I hit an issue (https://github.com/tumblr/collins/issues/436) that I am exploring with Collins team. 

I think we can close this issue since we have a test verifying the functionality. Let me know in case you feel otherwise and we can reopen this one.
